import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from '@mui/material/styles';
import WalletProvider from '@/app/providers/WalletProvider';
import { lightTheme } from '@/theme';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={lightTheme}>
            <WalletProvider>
              {children}
            </WalletProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
        </body>
    </html>
  );
}
